-- =============================================================================
-- Supabase Schema & pgvector Setup for Personal Knowledge Assistant
-- Run this in your Supabase SQL Editor to set up all tables, indexes, and RPCs.
-- All statements are idempotent and non-destructive.
-- =============================================================================

-- 1. Enable the pgvector extension to work with embedding vectors
create extension if not exists vector;

-- 2. Create the document chunks table (stores text + 384-dimensional embeddings)
create table if not exists public.chunks (
  id bigint generated by default as identity primary key,
  text text not null,
  embedding vector(384),
  user_id text, -- Added for Clerk userId scoping
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Create the conversations table
create table if not exists public.conversations (
  id uuid default gen_random_uuid() primary key,
  title text not null,
  user_id text, -- Added for Clerk userId scoping
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Create the messages table
create table if not exists public.messages (
  id text primary key, -- Text because the AI SDK generates string IDs (e.g. "msg_123")
  conversation_id uuid references public.conversations(id) on delete cascade not null,
  role text not null check (role in ('user', 'assistant', 'system')),
  content text not null,
  sources jsonb, -- To store the retrieved SearchResult[]
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Create indexes for high-performance lookups
create index if not exists messages_conversation_id_idx on public.messages(conversation_id);
create index if not exists conversations_created_at_idx on public.conversations(created_at desc);
create index if not exists chunks_created_at_idx on public.chunks(created_at desc);
create index if not exists chunks_user_id_idx on public.chunks(user_id); -- Added for Clerk userId queries
create index if not exists conversations_user_id_idx on public.conversations(user_id); -- Added for Clerk userId queries

-- 6. Create HNSW vector index on chunks embedding for fast approximate nearest neighbor search
-- 384 dimensions matches sentence-transformers/all-MiniLM-L6-v2 output size.
create index if not exists chunks_embedding_hnsw_idx 
  on public.chunks 
  using hnsw (embedding vector_cosine_ops);

-- 7. Create or replace the vector search RPC function
create or replace function match_chunks (
  query_embedding vector(384),
  p_user_id text, -- Added for Clerk userId scoping
  match_count int default 5
)
returns table (
  id bigint,
  text text,
  similarity float
)
language sql stable
as $$
  select
    chunks.id,
    chunks.text,
    1 - (chunks.embedding <=> query_embedding) as similarity
  from chunks
  where chunks.user_id = p_user_id
  order by chunks.embedding <=> query_embedding
  limit match_count;
$$;

-- 8. Row Level Security (RLS) configuration
alter table public.chunks enable row level security;
alter table public.conversations enable row level security;
alter table public.messages enable row level security;

-- Non-destructive policies for public read access
do $$
begin
  if not exists (
    select 1 from pg_policies where tablename = 'chunks' and policyname = 'Allow public read access to chunks'
  ) then
    create policy "Allow public read access to chunks" on public.chunks for select using (true);
  end if;

  if not exists (
    select 1 from pg_policies where tablename = 'conversations' and policyname = 'Allow public read access to conversations'
  ) then
    create policy "Allow public read access to conversations" on public.conversations for select using (true);
  end if;

  if not exists (
    select 1 from pg_policies where tablename = 'messages' and policyname = 'Allow public read access to messages'
  ) then
    create policy "Allow public read access to messages" on public.messages for select using (true);
  end if;
end $$;

