import { createClient } from "@supabase/supabase-js";
import { DatabaseError, RetrievalError } from "./errors";

// Make sure to add these to your .env.local:
// SUPABASE_URL=https://your-project-ref.supabase.co
// SUPABASE_SERVICE_ROLE_KEY=eyJ...
// 
// Note: We use the SERVICE_ROLE key here because this runs server-side 
// and we want to bypass Row Level Security (RLS) for inserting chunks.
// If you only use the anon key, you'll need to configure RLS policies in Supabase.
const supabaseUrl = process.env.SUPABASE_URL || "";
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || "";

export const supabase = createClient(supabaseUrl, supabaseKey);

export interface DbChunk {
  id: number;
  text: string;
  embedding: number[];
  created_at: string;
}

/**
 * 1. Insert a chunk + embedding into the database
 */
export async function insertChunk(text: string, embedding: number[], userId: string) {
  const { data, error } = await supabase
    .from("chunks")
    .insert([
      {
        text,
        // Supabase/pgvector automatically handles the number[] to vector cast
        embedding, 
        user_id: userId,
      },
    ])
    .select()
    .single();

  if (error) {
    throw new DatabaseError(
      `insertChunk failed: ${error.message}`,
      "Failed to save document chunk. Please try again."
    );
  }

  return data as DbChunk;
}

/**
 * 1b. Batch insert multiple chunks + embeddings into the database.
 * Batches inserts into manageable chunk sets (default 100) to avoid payload/connection limits.
 */
export async function insertChunksBatch(
  chunks: { text: string; embedding: number[] }[],
  userId: string,
  batchSize: number = 100
): Promise<DbChunk[]> {
  if (chunks.length === 0) return [];

  const results: DbChunk[] = [];

  for (let i = 0; i < chunks.length; i += batchSize) {
    const batch = chunks.slice(i, i + batchSize).map((chunk) => ({
      text: chunk.text,
      embedding: chunk.embedding,
      user_id: userId,
    }));

    const { data, error } = await supabase
      .from("chunks")
      .insert(batch)
      .select();

    if (error) {
      throw new DatabaseError(
        `insertChunksBatch failed on batch at index ${i}: ${error.message}`,
        "Failed to save document chunks. Please try again."
      );
    }

    if (data) {
      results.push(...(data as DbChunk[]));
    }
  }

  return results;
}

export interface SearchResult {
  id: number;
  text: string;
  similarity: number;
}

/**
 * 2. Search for the top-k most similar chunks
 * 
 * Note: Supabase's auto-generated REST API doesn't support ordering by 
 * vector distance directly yet. We have to call a custom Postgres function 
 * (RPC) that uses the `<=>` operator under the hood.
 * 
 * You'll need to run this SQL in your Supabase SQL editor first:
 * 
 * create or replace function match_chunks (
 *   query_embedding vector(384),
 *   match_count int default 5
 * )
 * returns table (
 *   id bigint,
 *   text text,
 *   similarity float
 * )
 * language sql stable
 * as $$
 *   select
 *     chunks.id,
 *     chunks.text,
 *     1 - (chunks.embedding <=> query_embedding) as similarity
 *   from chunks
 *   order by chunks.embedding <=> query_embedding
 *   limit match_count;
 * $$;
 */
export async function searchChunks(
  queryEmbedding: number[],
  userId: string,
  matchCount: number = 5
): Promise<SearchResult[]> {
  const { data, error } = await supabase.rpc("match_chunks", {
    query_embedding: queryEmbedding,
    p_user_id: userId,
    match_count: matchCount,
  });

  if (error) {
    throw new RetrievalError(
      `searchChunks RPC failed: ${error.message}`
    );
  }

  return data as SearchResult[];
}

// ── Persistence: Conversations & Messages ────────────────────────────────────

export interface DbConversation {
  id: string; // UUID generated by Supabase
  title: string;
  user_id?: string;
  created_at: string;
}

export interface DbMessage {
  id: string; // Text ID generated by Vercel AI SDK
  conversation_id: string;
  role: 'user' | 'assistant' | 'system';
  content: string;
  sources: SearchResult[] | null;
  created_at: string;
}

export async function createConversation(title: string, userId: string): Promise<DbConversation> {
  const { data, error } = await supabase
    .from("conversations")
    .insert([{ title, user_id: userId }])
    .select()
    .single();

  if (error) throw new DatabaseError(`createConversation failed: ${error.message}`);
  return data as DbConversation;
}

export async function getConversations(userId: string): Promise<DbConversation[]> {
  const { data, error } = await supabase
    .from("conversations")
    .select("*")
    .eq("user_id", userId)
    .order("created_at", { ascending: false });

  if (error) throw new DatabaseError(`getConversations failed: ${error.message}`);
  return data as DbConversation[];
}

export async function deleteConversation(conversationId: string, userId: string): Promise<void> {
  // Verify ownership of the conversation first
  const { data: convo, error: convoError } = await supabase
    .from("conversations")
    .select("user_id")
    .eq("id", conversationId)
    .single();

  if (convoError) {
    if (convoError.code === "PGRST116") {
      // Gracefully handle nonexistent conversation
      return;
    }
    throw new DatabaseError(`deleteConversation ownership check failed: ${convoError.message}`);
  }

  if (!convo || convo.user_id !== userId) {
    throw new DatabaseError("Conversation not found or access denied");
  }

  const { error } = await supabase
    .from("conversations")
    .delete()
    .eq("id", conversationId)
    .eq("user_id", userId);

  if (error) {
    throw new DatabaseError(`deleteConversation failed: ${error.message}`);
  }
}

export async function getMessages(conversationId: string, userId: string): Promise<DbMessage[]> {
  // Verify ownership of the conversation first
  const { data: convo, error: convoError } = await supabase
    .from("conversations")
    .select("user_id")
    .eq("id", conversationId)
    .single();

  if (convoError || !convo || convo.user_id !== userId) {
    throw new DatabaseError("Conversation not found or access denied");
  }

  const { data, error } = await supabase
    .from("messages")
    .select("*")
    .eq("conversation_id", conversationId)
    .order("created_at", { ascending: true });

  if (error) throw new DatabaseError(`getMessages failed: ${error.message}`);
  return data as DbMessage[];
}

export async function saveMessage(
  message: {
    id: string;
    conversation_id: string;
    role: 'user' | 'assistant' | 'system';
    content: string;
    sources?: SearchResult[] | null;
  },
  userId: string
) {
  // Verify ownership of the conversation first
  const { data: convo, error: convoError } = await supabase
    .from("conversations")
    .select("user_id")
    .eq("id", message.conversation_id)
    .single();

  if (convoError || !convo || convo.user_id !== userId) {
    throw new DatabaseError("Conversation not found or access denied");
  }

  const { error } = await supabase
    .from("messages")
    .insert([{
      id: message.id,
      conversation_id: message.conversation_id,
      role: message.role,
      content: message.content,
      sources: message.sources || null,
    }]);

  if (error) throw new DatabaseError(`saveMessage failed: ${error.message}`);
}


/**
 * Check if the user has any chunks/documents uploaded
 */
export async function countUserChunks(userId: string): Promise<number> {
  const { count, error } = await supabase
    .from("chunks")
    .select("*", { count: "exact", head: true })
    .eq("user_id", userId);

  if (error) {
    console.error("[Supabase] countUserChunks failed:", error.message);
    return 0;
  }

  return count || 0;
}

